name: Check pull request

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: check-pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test native binaries
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-native-binaries.yml

  check:
    name: Check tests
    needs: build-and-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Fail if build-and-test failed
        if: needs.build-and-test.result != 'success'
        run: exit 1
